import { Poppins } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "700"], // Add required weights
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}


// import { Geist, Geist_Mono } from "next/font/google";
//  import "./globals.css";
 
//  const geistSans = Geist({
//    variable: "--font-geist-sans",
//    subsets: ["latin"],
//  });
 
//  const geistMono = Geist_Mono({
//    variable: "--font-geist-mono",
//    subsets: ["latin"],
//  });
 
//  export const metadata = {
//    title: "Create Next App",
//    description: "Generated by create next app",
//  };
 
//  export default function RootLayout({ children }) {
//    return (
//      <html lang="en">
//        <body
//          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//        >
//          {children}
//        </body>
//      </html>
//    );
//  }